# https://taskfile.dev

version: '3'

env:
  TARGET: vss

tasks:
  
  doc:
    desc: Update module document
    cmds:
      - v doc -o docs/ -f markdown .
      - mv docs/index.md docs/vdotenv.md

  test:
    desc: Run test
    cmds:
      - v test .

  vet:
    desc: Report suspicious code constructs
    cmds:
      - v vet *.v

  format:
    desc: Format .v files
    cmds:
      - v fmt -w *.v
    
  clean:
    desc: Clean test files
    cmds:
      - rm -rf dist/
  
  dist:
    desc: Mkdir dist
    cmds:
      - mkdir -p dist
      - task: build
      - cp $TARGET dist/

  build:
    desc: Build vss
    cmds:
      - v . -o $TARGET
    
  example:
    desc: Setup for example
    cmds:
      - rm example/vss
      - task: build
      - cp vss example
