name: release

on:
  push:
    tags:
    - "v*.*.*"

jobs:
  build:
    strategy:
      matrix:
        os: ["ubuntu-latest", "macos-latest", "windows-latest"]
    runs-on: ${{ matrix.os }}

    steps:
      - name: Install V
        uses: vlang/setup-v@v1
        with:
          check-latest: true

      - name: Install Task
        uses: arduino/setup-task@v1

      - name: Checkout ${{ github.event.repository.name }}
        uses: actions/checkout@v2

      - name: Install deps
        run: task setup

      - name: Build ${{ github.event.repository.name }}
        run: task dist

      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            dist/**
